included:
  - Lib/KeyHolder
  - Lib/KeyHolderTests
opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - prohibited_super_call
  - vertical_parameter_alignment_on_call
  - unneeded_parentheses_in_closure_argument
  - extension_access_modifier
  - literal_expression_end_indentation
  - joined_default_parameter
  - contains_over_first_not_nil
  - override_in_extension
  - private_action
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - single_test_class
  - sorted_first_last
  - yoda_condition
disabled_rules:
  - nesting
  - function_parameter_count
identifier_name:
  excluded:
    - i
    - x
    - y
line_length: 300
