name: Danger
on: 
  pull_request:
  push:
    branches:
      - master
jobs:
  danger:
    runs-on: macos-latest
    # https://github.com/danger/danger/issues/1103
    if: (github.event.pull_request.head.repo.fork == false)
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Setup ruby
      uses: ruby/setup-ruby@c4e5b1316158f92e3d49443a9d58b31d25ac0f8f # v1.306.0
      with:
        ruby-version: '3.4'
        bundler-cache: true
    - name: Cache Mint
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: .mint
        key: ${{ runner.os }}-mint-${{ env.SWIFTLINT_VERSION }}
        restore-keys: |
          ${{ runner.os }}-mint-
    - name: Install Mint and Packages
      run: |
        brew install mint
        mint install realm/SwiftLint@${{ env.SWIFTLINT_VERSION }}
    - name: Run Danger
      run: bundle exec danger
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    env:
      MINT_PATH: .mint/lib
      MINT_LINK_PATH: .mint/bin
      SWIFTLINT_VERSION: 0.63.2
      DEVELOPER_DIR: /Applications/Xcode_26.2.app/Contents/Developer
