name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1

    - name: Submodule init
      run: git submodule update --init --recursive

    - name: Xcode select
      run: sudo xcode-select -s /Applications/Xcode_10.3.app

    - name: Run tests
      run: |
        bundle install
        bundle exec fastlane scan
