name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Xcode select
      run: sudo xcode-select -s /Applications/Xcode_11.2.app

    - name: Run tests
      run: |
        bundle install
        bundle exec fastlane scan
