name: Xcode-Build
on: [push, pull_request]
jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Xcode select
      run: sudo xcode-select -s /Applications/Xcode_11.4.app

    - name: Build and Test
      run: |
        set -o pipefail
        xcodebuild build-for-testing test-without-building \
          -workspace "$PROJECT" \
          -scheme "$SCHEME" \
          -sdk "$SDK" \
          -destination "$DESTINATION" \
          -configuration Debug \
          ENABLE_TESTABILITY=YES | xcpretty -c;
      env:
        PROJECT: KeyHolder.xcworkspace
        SCHEME: KeyHolder
        SDK: macosx
        DESTINATION: arch=x86_64
