name: Xcode-Build
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, macos-13]
        xcode: ['14.2', '15.0']
        exclude:
          - os: macos-12
            xcode: '15.0'
    env:
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer"
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build and Test
      run: |
        set -o pipefail
        xcodebuild build-for-testing test-without-building \
          -workspace "$PROJECT" \
          -scheme "$SCHEME" \
          -sdk "$SDK" \
          -configuration Debug \
          ENABLE_TESTABILITY=YES | xcpretty -c;
      env:
        PROJECT: KeyHolder.xcworkspace
        SCHEME: KeyHolder
        SDK: macosx
